import { Product, GalleryProject, Advantage, TimelineStep } from './types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'arz-zanaves',
    name: 'АРЗ (Антрактно-раздвижной занавес)',
    category: 'curtains',
    shortDescription: 'Основной раздвижной занавес для сцены театра',
    fullDescription: 'АРЗ — антрактно-раздвижной занавес, основной элемент театральной одежды сцены. Изготавливается из плотного бархата или велюра. Оснащается механизмом плавного раздвижения. Индивидуальный пошив по размерам вашей сцены.',
    images: ['/images/products/curtain-1.jpg', '/images/products/curtain-1.jpg', '/images/products/curtain-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат театральный, велюр' },
      { label: 'Плотность ткани', value: '350-450 г/м²' },
      { label: 'Огнестойкость', value: 'Соответствует ГОСТ' },
      { label: 'Способ открывания', value: 'Раздвижной' },
      { label: 'Крепление', value: 'Штанкет, направляющие' },
    ],
    features: ['Индивидуальный пошив по размерам', 'Соответствие ГОСТ', 'Гарантия 2 года', 'Доставка по всей России'],
    minPrice: 85000,
    maxPrice: 450000,
    unit: 'комплект',
    inStock: true,
    popular: true,
  },
  {
    id: '2',
    slug: 'arlekin',
    name: 'Арлекин',
    category: 'borders',
    shortDescription: 'Декоративный падуг для верхней части портала',
    fullDescription: 'Арлекин — горизонтальный элемент оформления верхней части портала сцены. Служит для маскировки осветительного оборудования и создания завершенного вида сценического портала. Изготавливается в едином стиле с занавесом.',
    images: ['/images/products/borders-1.jpg', '/images/products/borders-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат, велюр' },
      { label: 'Плотность ткани', value: '300-400 г/м²' },
      { label: 'Огнестойкость', value: 'Соответствует ГОСТ' },
      { label: 'Высота', value: '1-2.5 м' },
      { label: 'Крепление', value: 'Штанкет' },
    ],
    features: ['Единый стиль с занавесом', 'Соответствие ГОСТ', 'Гарантия 2 года'],
    minPrice: 35000,
    maxPrice: 150000,
    unit: 'штука',
    inStock: true,
    popular: true,
  },
  {
    id: '3',
    slug: 'kulisy',
    name: 'Кулиса',
    category: 'wings',
    shortDescription: 'Боковые драпировки для маскировки закулисного пространства',
    fullDescription: 'Кулисы размещаются по бокам сцены и служат для скрытия технического пространства, а также для выхода артистов. Изготавливаются в едином стиле с основным занавесом.',
    images: ['/images/products/wings-1.jpg', '/images/products/wings-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат, велюр, молескин' },
      { label: 'Плотность ткани', value: '300-400 г/м²' },
      { label: 'Огнестойкость', value: 'Соответствует ГОСТ' },
      { label: 'Количество пар', value: 'от 3 до 6 пар' },
      { label: 'Крепление', value: 'Штанга, направляющие' },
    ],
    features: ['Комплект от 3 пар', 'Единый стиль с занавесом', 'Гарантия 2 года'],
    minPrice: 35000,
    maxPrice: 180000,
    unit: 'пара',
    inStock: true,
    popular: true,
  },
  {
    id: '4',
    slug: 'paduga',
    name: 'Падуга',
    category: 'borders',
    shortDescription: 'Горизонтальные драпировки для маскировки верхнего пространства',
    fullDescription: 'Падуги — горизонтальные полосы ткани, закрывающие верхнюю часть сцены и осветительное оборудование. Создают единый визуальный стиль с кулисами и занавесом.',
    images: ['/images/products/borders-1.jpg', '/images/products/borders-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат, велюр' },
      { label: 'Плотность ткани', value: '300-400 г/м²' },
      { label: 'Огнестойкость', value: 'Соответствует ГОСТ' },
      { label: 'Высота', value: '1-2.5 м' },
      { label: 'Крепление', value: 'Штанкет' },
    ],
    features: ['Комплект от 3 штук', 'Регулируемая высота', 'Гарантия 2 года'],
    minPrice: 25000,
    maxPrice: 120000,
    unit: 'штука',
    inStock: true,
    popular: false,
  },
  {
    id: '5',
    slug: 'zadnik',
    name: 'Задник',
    category: 'backdrops',
    shortDescription: 'Фоновое полотно для оформления глубины сцены',
    fullDescription: 'Задник сцены создает визуальную глубину и служит фоном для театрального действия. Может быть однотонным или предназначенным для проекции.',
    images: ['/images/products/backdrop-1.jpg', '/images/products/backdrop-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Габардин, бязь, ПВХ' },
      { label: 'Плотность ткани', value: '200-350 г/м²' },
      { label: 'Огнестойкость', value: 'Соответствует ГОСТ' },
      { label: 'Тип', value: 'Глухой, для проекции' },
      { label: 'Крепление', value: 'Штанкет, люверсы' },
    ],
    features: ['Подходит для проекции', 'Бесшовное полотно до 5м', 'Гарантия 2 года'],
    minPrice: 45000,
    maxPrice: 280000,
    unit: 'комплект',
    inStock: true,
    popular: true,
  },
  {
    id: '6',
    slug: 'portal',
    name: 'Портал',
    category: 'drapes',
    shortDescription: 'Декоративное оформление портала сцены',
    fullDescription: 'Портал — комплексное оформление проема сцены, включающее боковые элементы и верхнюю часть. Создает парадный вид сцены и скрывает техническое оборудование.',
    images: ['/images/products/drapes-1.jpg', '/images/products/drapes-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат премиум, велюр' },
      { label: 'Плотность ткани', value: '350-450 г/м²' },
      { label: 'Декор', value: 'Ламбрекен, кисти, бахрома' },
      { label: 'Огнестойкость', value: 'Соответствует ГОСТ' },
      { label: 'Крепление', value: 'Каркас, штанкет' },
    ],
    features: ['Премиум материалы', 'Индивидуальный дизайн', 'Гарантия 2 года'],
    minPrice: 150000,
    maxPrice: 800000,
    unit: 'комплект',
    inStock: true,
    popular: true,
  },
]

export const galleryProjects: GalleryProject[] = [
  {
    id: '1',
    title: 'ДК Протвино',
    location: 'Протвино',
    category: 'Дома культуры',
    image: '/images/gallery/dk-gorky.jpg',
    year: 2024,
  },
  {
    id: '2',
    title: 'ДК Силикатный',
    location: 'Московская область',
    category: 'Дома культуры',
    image: '/images/gallery/zaryadye.jpg',
    year: 2024,
  },
  {
    id: '3',
    title: 'Дворец творчества',
    location: 'Рязань',
    category: 'Дворцы творчества',
    image: '/images/gallery/novosibirsk-drama.jpg',
    year: 2023,
  },
  {
    id: '4',
    title: 'Студенческий ДК',
    location: 'Россия',
    category: 'Дома культуры',
    image: '/images/gallery/kazan-palace.jpg',
    year: 2023,
  },
]

export const advantages: Advantage[] = [
  {
    icon: 'factory',
    title: 'Собственное производство',
    description: 'Полный цикл изготовления на современном оборудовании в России',
  },
  {
    icon: 'fire',
    title: 'Соответствие ГОСТ',
    description: 'Огнестойкость и безопасность по ГОСТ для театральных тканей',
  },
  {
    icon: 'ruler',
    title: 'Индивидуальный пошив',
    description: 'Изготовление по точным размерам вашей сцены',
  },
  {
    icon: 'truck',
    title: 'Доставка по России',
    description: 'Доставка в любой регион Российской Федерации',
  },
  {
    icon: 'shield',
    title: 'Гарантия 2 года',
    description: 'Официальная гарантия на все изделия',
  },
  {
    icon: 'clock',
    title: '15+ лет опыта',
    description: 'Более 15 лет работы на рынке театрального оборудования',
  },
]

export const timelineSteps: TimelineStep[] = [
  {
    step: 1,
    title: 'Заявка и консультация',
    description: 'Оставьте заявку на сайте или позвоните. Наш специалист свяжется с вами для уточнения деталей проекта.',
  },
  {
    step: 2,
    title: 'Проект и смета',
    description: 'Подготовка детального технического проекта и коммерческого предложения с фиксированной ценой.',
  },
  {
    step: 3,
    title: 'Производство',
    description: 'Изготовление изделий на собственном производстве с контролем качества на каждом этапе.',
  },
  {
    step: 4,
    title: 'Доставка',
    description: 'Доставка в любой регион России.',
  },
  {
    step: 5,
    title: 'Приемка и гарантия',
    description: 'Подписание актов, передача документации и начало гарантийного обслуживания.',
  },
]

export const venueTypes = [
  { value: 'theater', label: 'Театр' },
  { value: 'concert-hall', label: 'Концертный зал' },
  { value: 'culture-house', label: 'Дом культуры' },
  { value: 'conference', label: 'Конференц-зал' },
  { value: 'school', label: 'Школа / Учебное заведение' },
  { value: 'event-hall', label: 'Банкетный зал' },
  { value: 'other', label: 'Другое' },
]

export const clothingTypes = [
  { value: 'arz', label: 'АРЗ (Антрактно-раздвижной занавес)' },
  { value: 'backdrop', label: 'Задник' },
  { value: 'wings', label: 'Кулисы' },
  { value: 'borders', label: 'Падуги' },
  { value: 'portal', label: 'Портал' },
  { value: 'arlekin', label: 'Арлекин' },
  { value: 'full-set', label: 'Полный комплект' },
  { value: 'other', label: 'Другое' },
]

export const fabricTypes = [
  { value: 'gabardine', label: 'Габардин' },
  { value: 'velvet', label: 'Бархат' },
  { value: 'blackout', label: 'Блэкаут' },
  { value: 'unknown', label: 'Нужна консультация' },
]

export const mountingTypes = [
  { value: 'self-install', label: 'Самостоятельно' },
  { value: 'consultation', label: 'Нужна консультация' },
]
