import { Product, GalleryProject, Advantage, TimelineStep } from './types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'antractniy-zanaves',
    name: 'Антрактный занавес',
    category: 'curtains',
    shortDescription: 'Классический раздвижной занавес для сцены театра',
    fullDescription: 'Антрактный занавес — основной элемент театральной одежды сцены. Изготавливается из плотного бархата или велюра с возможностью нанесения вышивки, аппликации или театральной символики. Оснащается механизмом плавного раздвижения.',
    images: ['/images/products/curtain-1.jpg', '/images/products/curtain-1.jpg', '/images/products/curtain-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат театральный, велюр' },
      { label: 'Плотность ткани', value: '350-450 г/м²' },
      { label: 'Огнестойкость', value: 'Г1 (слабогорючий)' },
      { label: 'Способ открывания', value: 'Раздвижной, подъемный' },
      { label: 'Крепление', value: 'Штанкет, направляющие' },
    ],
    features: ['Индивидуальный пошив по размерам', 'Огнезащитная пропитка', 'Монтаж под ключ', 'Гарантия 5 лет'],
    minPrice: 85000,
    maxPrice: 450000,
    unit: 'комплект',
    inStock: true,
    popular: true,
  },
  {
    id: '2',
    slug: 'zadnik-sceny',
    name: 'Задник сцены',
    category: 'backdrops',
    shortDescription: 'Фоновое полотно для оформления глубины сцены',
    fullDescription: 'Задник сцены создает визуальную глубину и служит фоном для театрального действия. Может быть однотонным, с художественной росписью или предназначенным для проекции.',
    images: ['/images/products/backdrop-1.jpg', '/images/products/backdrop-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Габардин, бязь, ПВХ' },
      { label: 'Плотность ткани', value: '200-350 г/м²' },
      { label: 'Огнестойкость', value: 'Г1-Г2' },
      { label: 'Тип', value: 'Глухой, для проекции' },
      { label: 'Крепление', value: 'Штанкет, люверсы' },
    ],
    features: ['Художественная роспись', 'Подходит для проекции', 'Бесшовное полотно до 5м'],
    minPrice: 45000,
    maxPrice: 280000,
    unit: 'комплект',
    inStock: true,
    popular: true,
  },
  {
    id: '3',
    slug: 'kulisy-bokovye',
    name: 'Кулисы боковые',
    category: 'wings',
    shortDescription: 'Боковые драпировки для маскировки закулисного пространства',
    fullDescription: 'Кулисы размещаются по бокам сцены и служат для скрытия технического пространства, а также для выхода артистов. Изготавливаются в едином стиле с основным занавесом.',
    images: ['/images/products/wings-1.jpg', '/images/products/wings-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат, велюр, молескин' },
      { label: 'Плотность ткани', value: '300-400 г/м²' },
      { label: 'Огнестойкость', value: 'Г1' },
      { label: 'Количество пар', value: 'от 3 до 6 пар' },
      { label: 'Крепление', value: 'Штанга, направляющие' },
    ],
    features: ['Комплект от 3 пар', 'Единый стиль с занавесом', 'Возможность передвижения'],
    minPrice: 35000,
    maxPrice: 180000,
    unit: 'пара',
    inStock: true,
    popular: false,
  },
  {
    id: '4',
    slug: 'padugi',
    name: 'Падуги',
    category: 'borders',
    shortDescription: 'Горизонтальные драпировки для маскировки верхнего пространства',
    fullDescription: 'Падуги — горизонтальные полосы ткани, закрывающие верхнюю часть сцены и осветительное оборудование. Создают единый визуальный стиль с кулисами и занавесом.',
    images: ['/images/products/borders-1.jpg', '/images/products/borders-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат, велюр' },
      { label: 'Плотность ткани', value: '300-400 г/м²' },
      { label: 'Огнестойкость', value: 'Г1' },
      { label: 'Высота', value: '1-2.5 м' },
      { label: 'Крепление', value: 'Штанкет' },
    ],
    features: ['Комплект от 3 штук', 'Регулируемая высота', 'Огнезащитная обработка'],
    minPrice: 25000,
    maxPrice: 120000,
    unit: 'штука',
    inStock: true,
    popular: false,
  },
  {
    id: '5',
    slug: 'gorizont-sceny',
    name: 'Горизонт сцены',
    category: 'cycloramas',
    shortDescription: 'Циклорама для создания эффекта бесконечного пространства',
    fullDescription: 'Горизонт (циклорама) — изогнутый фон сцены, создающий иллюзию бесконечного пространства. Идеален для световых эффектов, проекций и хромакея.',
    images: ['/images/products/cyclorama-1.jpg', '/images/products/cyclorama-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'ПВХ, специальный текстиль' },
      { label: 'Цвет', value: 'Белый, синий, черный' },
      { label: 'Конструкция', value: 'Жесткая, гибкая' },
      { label: 'Радиус', value: 'от 2 м' },
      { label: 'Крепление', value: 'Каркас, подвес' },
    ],
    features: ['Бесшовное покрытие', 'Подходит для хромакея', 'Равномерное освещение'],
    minPrice: 120000,
    maxPrice: 650000,
    unit: 'комплект',
    inStock: true,
    popular: true,
  },
  {
    id: '6',
    slug: 'drapirovka-dekorativnaya',
    name: 'Декоративная драпировка',
    category: 'drapes',
    shortDescription: 'Элементы оформления для создания атмосферы мероприятия',
    fullDescription: 'Декоративные драпировки используются для оформления залов, фойе и сценического пространства. Создают торжественную атмосферу и могут быть выполнены в любой цветовой гамме.',
    images: ['/images/products/drapes-1.jpg', '/images/products/drapes-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Атлас, шифон, органза, бархат' },
      { label: 'Плотность ткани', value: '100-350 г/м²' },
      { label: 'Огнестойкость', value: 'По запросу' },
      { label: 'Цвета', value: 'Любые по каталогу' },
      { label: 'Крепление', value: 'Разное' },
    ],
    features: ['Любые цвета', 'Аренда и продажа', 'Быстрое изготовление'],
    minPrice: 15000,
    maxPrice: 95000,
    unit: 'погонный метр',
    inStock: true,
    popular: false,
  },
  {
    id: '7',
    slug: 'superzanaves',
    name: 'Суперзанавес',
    category: 'curtains',
    shortDescription: 'Парадный занавес с декоративными элементами',
    fullDescription: 'Суперзанавес — парадный элемент оформления сцены, располагающийся перед антрактным занавесом. Украшается ламбрекенами, кистями, вышивкой и другими декоративными элементами.',
    images: ['/images/products/super-curtain-1.jpg', '/images/products/super-curtain-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Бархат премиум, парча' },
      { label: 'Плотность ткани', value: '400-550 г/м²' },
      { label: 'Декор', value: 'Ламбрекен, кисти, бахрома' },
      { label: 'Вышивка', value: 'Золотая, серебряная нить' },
      { label: 'Крепление', value: 'Штанкет механический' },
    ],
    features: ['Премиум материалы', 'Ручная вышивка', 'Эксклюзивный дизайн'],
    minPrice: 250000,
    maxPrice: 1500000,
    unit: 'комплект',
    inStock: true,
    popular: true,
  },
  {
    id: '8',
    slug: 'protivopozharniy-zanaves',
    name: 'Противопожарный занавес',
    category: 'curtains',
    shortDescription: 'Огнестойкий защитный занавес класса НГ',
    fullDescription: 'Противопожарный занавес — обязательный элемент безопасности для театров и концертных залов вместимостью более 800 человек. Изготавливается из негорючих материалов и соответствует всем нормам пожарной безопасности.',
    images: ['/images/products/fire-curtain-1.jpg', '/images/products/fire-curtain-1.jpg'],
    specifications: [
      { label: 'Материал', value: 'Стекловолокно, металл' },
      { label: 'Класс горючести', value: 'НГ (негорючий)' },
      { label: 'Сертификат', value: 'ГОСТ, EI 60' },
      { label: 'Механизм', value: 'Автоматический, ручной' },
      { label: 'Привод', value: 'Электрический с УПС' },
    ],
    features: ['Сертификат МЧС', 'Автоматическое срабатывание', 'Обслуживание'],
    minPrice: 450000,
    maxPrice: 2500000,
    unit: 'комплект',
    inStock: true,
    popular: false,
  },
]

export const galleryProjects: GalleryProject[] = [
  {
    id: '1',
    title: 'Большой театр',
    location: 'Москва',
    category: 'Театры',
    image: '/images/gallery/bolshoi.jpg',
    year: 2023,
  },
  {
    id: '2',
    title: 'ДК им. Горького',
    location: 'Санкт-Петербург',
    category: 'Дома культуры',
    image: '/images/gallery/dk-gorky.jpg',
    year: 2023,
  },
  {
    id: '3',
    title: 'Концертный зал «Зарядье»',
    location: 'Москва',
    category: 'Концертные залы',
    image: '/images/gallery/zaryadye.jpg',
    year: 2022,
  },
  {
    id: '4',
    title: 'Областной драматический театр',
    location: 'Новосибирск',
    category: 'Театры',
    image: '/images/gallery/novosibirsk-drama.jpg',
    year: 2023,
  },
  {
    id: '5',
    title: 'Дворец съездов',
    location: 'Казань',
    category: 'Конференц-залы',
    image: '/images/gallery/kazan-palace.jpg',
    year: 2024,
  },
  {
    id: '6',
    title: 'Филармония',
    location: 'Екатеринбург',
    category: 'Концертные залы',
    image: '/images/gallery/ekb-philharmonic.jpg',
    year: 2024,
  },
]

export const advantages: Advantage[] = [
  {
    icon: 'factory',
    title: 'Собственное производство',
    description: 'Полный цикл изготовления на современном оборудовании в России',
  },
  {
    icon: 'fire',
    title: 'Огнезащитная обработка',
    description: 'Сертифицированная пропитка по ГОСТ, класс Г1',
  },
  {
    icon: 'ruler',
    title: 'Индивидуальный пошив',
    description: 'Изготовление по точным размерам вашей сцены',
  },
  {
    icon: 'truck',
    title: 'Доставка и монтаж',
    description: 'Профессиональная установка по всей России',
  },
  {
    icon: 'shield',
    title: 'Гарантия 5 лет',
    description: 'Официальная гарантия на все изделия и работы',
  },
  {
    icon: 'clock',
    title: 'Сроки от 14 дней',
    description: 'Быстрое изготовление без потери качества',
  },
]

export const timelineSteps: TimelineStep[] = [
  {
    step: 1,
    title: 'Заявка и консультация',
    description: 'Оставьте заявку на сайте или позвоните. Наш специалист свяжется с вами для уточнения деталей проекта.',
  },
  {
    step: 2,
    title: 'Выезд замерщика',
    description: 'Бесплатный выезд специалиста для точных замеров и оценки технических условий сцены.',
  },
  {
    step: 3,
    title: 'Проект и смета',
    description: 'Подготовка детального технического проекта и коммерческого предложения с фиксированной ценой.',
  },
  {
    step: 4,
    title: 'Производство',
    description: 'Изготовление изделий на собственном производстве с контролем качества на каждом этапе.',
  },
  {
    step: 5,
    title: 'Доставка и монтаж',
    description: 'Доставка в любой регион России и профессиональный монтаж силами нашей бригады.',
  },
  {
    step: 6,
    title: 'Приемка и гарантия',
    description: 'Подписание актов, передача документации и начало гарантийного обслуживания.',
  },
]

export const venueTypes = [
  { value: 'theater', label: 'Театр' },
  { value: 'concert-hall', label: 'Концертный зал' },
  { value: 'culture-house', label: 'Дом культуры' },
  { value: 'conference', label: 'Конференц-зал' },
  { value: 'school', label: 'Школа / Учебное заведение' },
  { value: 'event-hall', label: 'Банкетный зал' },
  { value: 'other', label: 'Другое' },
]

export const clothingTypes = [
  { value: 'main-curtain', label: 'Главный занавес' },
  { value: 'backdrop', label: 'Задник' },
  { value: 'wings', label: 'Кулисы' },
  { value: 'borders', label: 'Падуги' },
  { value: 'cyclorama', label: 'Горизонт / Циклорама' },
  { value: 'drapes', label: 'Декоративные драпировки' },
  { value: 'fire-curtain', label: 'Противопожарный занавес' },
  { value: 'full-set', label: 'Полный комплект' },
]

export const fabricTypes = [
  { value: 'velvet', label: 'Бархат театральный' },
  { value: 'velour', label: 'Велюр' },
  { value: 'moleskin', label: 'Молескин' },
  { value: 'gabardine', label: 'Габардин' },
  { value: 'satin', label: 'Атлас' },
  { value: 'pvc', label: 'ПВХ' },
  { value: 'unknown', label: 'Нужна консультация' },
]

export const mountingTypes = [
  { value: 'with-mounting', label: 'Да, нужен монтаж' },
  { value: 'self-install', label: 'Нет, установим сами' },
  { value: 'consultation', label: 'Нужна консультация' },
]
